const DataSet = [{
    title:'개발은 아무나 할 수 있는 일이 아니다.',
    explain:'',
    link:[{linkPerson:'테크보이 워니',
    linkTitle:'이런 분들은 개발자 하지 마세요',
    linkUrl:'https://www.youtube.com/watch?v=AJ8rhNnoPSE',
    linkExplain:''},
    {linkPerson:'노마드 코더',
    linkTitle:'누구나 코딩을 할 수 있다? 5가지 팩폭 드림.',
    linkUrl:'https://www.youtube.com/watch?v=ThGbP9wgkz8',
    linkExplain:''},
    {linkPerson:'버클리 클라쓰',
    linkTitle:'솔직히 이런사람들 개발자 코딩 하지마세요 | 저는 엔지니어를 그만뒀습니다',
    linkUrl:'https://www.youtube.com/watch?v=6LZIPzemx3g',
    linkExplain:''}
]
},{
    title:'개발 분야, 그 끝은 어디인가?',
    explain:'',
    link:[{linkPerson:'삼평동연구소',
    linkTitle:'개발 분야, 얼마나 알고 계신가요? (feat. 진로 탐색 가이드)',
    linkUrl:'https://www.youtube.com/watch?v=wZ-djOD2FdE',
    linkExplain:''},
    {linkPerson:'드림코딩by엘리',
    linkTitle:'프론트엔드 개발자 백엔드 개발자 무엇을 선택할까? 공부 방법은? (Frontend vs Backend)',
    linkUrl:'https://www.youtube.com/watch?v=-y9h5yl7egE',
    linkExplain:''},
    {linkPerson:'노마드 코더',
    linkTitle:'풀스택 개발자가 정확히 뭔가요?',
    linkUrl:'https://www.youtube.com/watch?v=2HKO20NWE04',
    linkExplain:''}]
},{
    title:'독서실 가서 개발 서적 읽으면 되나요?',
    explain:'',
    link:[{linkPerson:'테크보이 워니',
    linkTitle:'코딩 무조건 빨리 배우는 법 - 제발 프로그래밍 기초 부터 차례대로 시작하지 마세요',
    linkUrl:'https://www.youtube.com/watch?v=SgGG4-nD4v8',
    linkExplain:''},
    {linkPerson:'노마드 코더',
    linkTitle:'풀스택 주니어 웹 개발자가 되려면? ver.2020',
    linkUrl:'https://www.youtube.com/watch?v=ODa9mY2bEEc',
    linkExplain:''},
    {linkPerson:'ZeroCho TV',
    linkTitle:'[제로초 토크] 첫 프로그래밍 공부 방법과 웹 개발 공부 순서',
    linkUrl:'https://www.youtube.com/watch?v=6qT8l1KRWY0',
    linkExplain:''}]
},{
    title:'첫 프로그래밍 언어 추천 좀..',
    explain:'',
    link:[{linkPerson:'삼평동연구소',
    linkTitle:'현직 개발자가 추천하는 꼭 배워야 할 프로그래밍 언어!',
    linkUrl:'https://www.youtube.com/watch?v=72gZEC0O1D8',
    linkExplain:''},
    {linkPerson:'노마드 코더',
    linkTitle:'어떤 언어부터 배워야할까? 5개 언어. 5분 개념탑재.',
    linkUrl:'https://www.youtube.com/watch?v=p_v_js0mxVc',
    linkExplain:''},
    {linkPerson:'테크보이 워니',
    linkTitle:'코딩/프로그래밍 처음 하는 사람이 배우기 제일 좋은 언어는? - C언어, 자바, 파이썬, 자바스크립트, 루비 비교',
    linkUrl:'https://www.youtube.com/watch?v=Wbjc8qAqHaI',
    linkExplain:''}]
},{
    title:'영상은 볼 만큼 봤으니, 시작하자!',
    explain:'',
    link:[{linkPerson:'',
    linkTitle:'',
    linkUrl:'',
    linkExplain:''},
    {linkPerson:'',
    linkTitle:'',
    linkUrl:'',
    linkExplain:''},
    {linkPerson:'',
    linkTitle:'',
    linkUrl:'',
    linkExplain:''}]
},{
    title:'추가로 보면 좋은 영상들',
    explain:'',
    link:[{linkPerson:'',
    linkTitle:'',
    linkUrl:'',
    linkExplain:''},
    {linkPerson:'',
    linkTitle:'',
    linkUrl:'',
    linkExplain:''},
    {linkPerson:'',
    linkTitle:'',
    linkUrl:'',
    linkExplain:''}],
    extraExplain:[{link:'',explain:''},{link:'',explain:''},{link:'',explain:''},{link:'',explain:''},{link:'',explain:''}]
}]